include = ["COMMON"]

# --------------------- #
# TCCON-specific Xgases #
# --------------------- #

[[xgas]]
xgas = "xco2_x2007"
gas = "co2"
prior_profile = { type = "specified", only_if_first = true, private_name = "prior_1co2", public_name = "prior_co2" }
prior_xgas = { type = "specified", only_if_first = true, private_name = "prior_xco2_x2007", public_name = "prior_xco2" }
ak = { type = "specified", only_if_first = true, private_name = "ak_xco2" }
slant_bin = { type = "specified", private_name = "ak_slant_xco2_bin" }

[[xgas]]
xgas = "xco2_x2019"
gas = "co2"
prior_profile = { type = "specified", only_if_first = true, private_name = "prior_1co2", public_name = "prior_co2" }
prior_xgas = { type = "specified", only_if_first = true, private_name = "prior_xco2_x2019", public_name = "prior_xco2" }
ak = { type = "specified", only_if_first = true, private_name = "ak_xco2" }
slant_bin = { type = "specified", private_name = "ak_slant_xco2_bin" }

[[xgas]]
xgas = "xwco2_x2007"
gas = "co2"
prior_profile = { type = "specified", only_if_first = true, private_name = "prior_1co2", public_name = "prior_co2" }
prior_xgas = { type = "specified", only_if_first = true, private_name = "prior_xwco2_x2007", public_name = "prior_xco2" }
ak = { type = "specified", only_if_first = true, private_name = "ak_xwco2" }
slant_bin = { type = "specified", private_name = "ak_slant_xwco2_bin" }

[[xgas]]
xgas = "xwco2_x2019"
gas = "co2"
prior_profile = { type = "specified", only_if_first = true, private_name = "prior_1co2", public_name = "prior_co2" }
prior_xgas = { type = "specified", only_if_first = true, private_name = "prior_xwco2_x2019", public_name = "prior_xco2" }
ak = { type = "specified", only_if_first = true, private_name = "ak_xwco2" }
slant_bin = { type = "specified", private_name = "ak_slant_xwco2_bin" }

[[xgas]]
xgas = "xlco2_x2007"
gas = "co2"
prior_profile = { type = "specified", only_if_first = true, private_name = "prior_1co2", public_name = "prior_co2" }
prior_xgas = { type = "specified", only_if_first = true, private_name = "prior_xlco2_x2007", public_name = "prior_xco2" }
ak = { type = "specified", only_if_first = true, private_name = "ak_xlco2" }
slant_bin = { type = "specified", private_name = "ak_slant_xlco2_bin" }

[[xgas]]
xgas = "xlco2_x2019"
gas = "co2"
prior_profile = { type = "specified", only_if_first = true, private_name = "prior_1co2", public_name = "prior_co2" }
prior_xgas = { type = "specified", only_if_first = true, private_name = "prior_xlco2_x2019", public_name = "prior_xco2" }
ak = { type = "specified", only_if_first = true, private_name = "ak_xlco2" }
slant_bin = { type = "specified", private_name = "ak_slant_xlco2_bin" }

[[xgas]]
xgas = "xhcl"
gas = "hcl"
ak = { type = "inferred", only_if_first = true, required = false }
traceability_scale = { type = "inferred", only_if_first = true, required = false }

# -------------- #
# Other settings #
# -------------- #
[global_attributes]
must_copy = [
    "source",
    "description",
    "file_creation",
    "title",
    "data_use_policy",
    "auxiliary_data_description",
    "more_information",
    "tccon_reference",
    "retrieval_reference",
    "contact",
    "data_revision",
    "file_format_information",
    "algorithm_version",
    "file_format_version",
]
copy_if_present = [
    "long_name",
    "location",
    "data_doi",
    "site_reference",
    "data_reference",
    "short_location",
]
